import {
  ArrowLeftIcon,
  ArrowRightIcon,
  ArticleIcon,
  BookOpenIcon,
  CalendarBlankIcon,
  CameraIcon,
  CaretDownIcon,
  ChatCircleTextIcon,
  CheckIcon,
  ClockIcon,
  CloudIcon,
  CrownIcon,
  DiamondIcon,
  DiscordLogoIcon,
  EnvelopeIcon,
  EnvelopeSimpleIcon,
  EyeIcon,
  FireIcon,
  GearIcon,
  GiftIcon,
  GithubLogoIcon,
  GlobeIcon,
  HandshakeIcon,
  HeartIcon,
  HouseIcon,
  ImageIcon,
  InfoIcon,
  InstagramLogoIcon,
  LightningIcon,
  LinkSimpleIcon,
  LinkedinLogoIcon,
  MagnifyingGlassIcon,
  MapPinIcon,
  MoneyIcon,
  MusicNoteIcon,
  PaintBrushIcon,
  PaletteIcon,
  PencilSimpleIcon,
  PlusIcon,
  QuestionIcon,
  ShieldCheckIcon,
  SmileyIcon,
  SparkleIcon,
  StarIcon,
  TagIcon,
  TiktokLogoIcon,
  TwitterLogoIcon,
  TwitchLogoIcon,
  UserIcon,
  WarningIcon,
  XIcon,
  YoutubeLogoIcon,
  type Icon,
} from '@phosphor-icons/react'

const registry: Record<string, Icon> = {
  House: HouseIcon,
  Image: ImageIcon,
  Palette: PaletteIcon,
  Question: QuestionIcon,
  EnvelopeSimple: EnvelopeSimpleIcon,
  Envelope: EnvelopeIcon,
  ChatCircleText: ChatCircleTextIcon,
  Cloud: CloudIcon,
  ArrowRight: ArrowRightIcon,
  InstagramLogo: InstagramLogoIcon,
  TiktokLogo: TiktokLogoIcon,
  DiscordLogo: DiscordLogoIcon,
  TwitterLogo: TwitterLogoIcon,
  YoutubeLogo: YoutubeLogoIcon,
  LinkSimple: LinkSimpleIcon,
  Gear: GearIcon,
  User: UserIcon,
  Star: StarIcon,
  Heart: HeartIcon,
  MagnifyingGlass: MagnifyingGlassIcon,
  GithubLogo: GithubLogoIcon,
  LinkedinLogo: LinkedinLogoIcon,
  TwitchLogo: TwitchLogoIcon,
  Globe: GlobeIcon,
  PaintBrush: PaintBrushIcon,
  PencilSimple: PencilSimpleIcon,
  Camera: CameraIcon,
  Sparkle: SparkleIcon,
  Diamond: DiamondIcon,
  Crown: CrownIcon,
  Lightning: LightningIcon,
  Fire: FireIcon,
  MusicNote: MusicNoteIcon,
  ArrowLeft: ArrowLeftIcon,
  CaretDown: CaretDownIcon,
  Check: CheckIcon,
  X: XIcon,
  Plus: PlusIcon,
  Info: InfoIcon,
  Warning: WarningIcon,
  Eye: EyeIcon,
  ShieldCheck: ShieldCheckIcon,
  Article: ArticleIcon,
  BookOpen: BookOpenIcon,
  Tag: TagIcon,
  CalendarBlank: CalendarBlankIcon,
  Clock: ClockIcon,
  MapPin: MapPinIcon,
  Money: MoneyIcon,
  Gift: GiftIcon,
  Handshake: HandshakeIcon,
  Smiley: SmileyIcon,
}

export function resolveIcon(name: string | undefined): Icon | undefined {
  if (!name) return undefined
  return registry[name]
}

export function isUrl(v: string | undefined): boolean {
  return !!v && (v.startsWith('http://') || v.startsWith('https://') || v.startsWith('blob:'))
}
